version: "3.7"
services:
  redis:
    image: public.ecr.aws/ubuntu/redis
    container_name: redis_datastore
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
  api:
    build: ./api
    container_name: bbq_api
    env_file: ./api/.env
    volumes:
      - ./api/:/usr/src/app/
    ports:
      - 8080:3000
    links:
      - redis:local_redis
  web:
    build: ./webapp
    container_name: react_web
    env_file: "./webapp/.env"
    volumes:
      - ./webapp:/usr/src/web
    ports:
      - 9000:3000
    links:
      - api:api
